/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.expert;

import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONObject;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.whu.tools.DBTools;
import com.whu.web.email.ContactBean;
import com.whu.web.eventbean.ExpertInfo;
import com.whu.web.user.ConfigUserForm;
import com.whu.web.user.UserBean;

/** 
 * MyEclipse Struts
 * Creation date: 03-03-2014
 * 
 * XDoclet definition:
 * @struts.action path="/configExpertAction" name="configExpertForm" parameter="method" scope="request" validate="true"
 */
public class ConfigExpertAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	public ActionForward save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");	
		ConfigExpertForm configExpertForm = (ConfigExpertForm)form;
		String operation = request.getParameter("operation");
		String addrID = request.getParameter("addrID");
		String expertName = configExpertForm.getName();
		String sex = configExpertForm.getSex();
		String age = configExpertForm.getAge();
		String title = configExpertForm.getTitle();
		String isPHD = configExpertForm.getIsPHD();
		String dept = configExpertForm.getDept();
		String specialty = configExpertForm.getSpecialty();
		String research = configExpertForm.getResearch();
		String faculty = configExpertForm.getFaculty();
		String phone = configExpertForm.getPhone();
		String email = configExpertForm.getEmail();
		String address = configExpertForm.getAddress();
		String other1 = configExpertForm.getOther1();
		String other2 = configExpertForm.getOther2();
		DBTools dbTool = new DBTools();
		String mark="expert";
		String sql = "";
		String sqlAddr="";
		String[] params = new String[0];
		String[] addrParams = new String[0];
		if(operation.equals("new"))
		{
			sql = "insert into SYS_EXPERTINFO(NAME,SEX,AGE,TITLE,ISPHD,DEPT,SPECIALTY,RESEARCH,PHONE,EMAIL,ADDRESS,FACULTY,OTHERONE,OTHERTWO) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?,?)";
			params = new String[]{expertName, sex, age, title, isPHD, dept, specialty, research, phone, email, address, faculty,other1,other2};
			sqlAddr="insert into TB_CONTACT(LOGINNAME,CONNAME,CONADDR) values(?, ?, ?)";
			addrParams = new String[]{mark, expertName, email};
		}
		else if(operation.equals("edit"))
		{
			String id = configExpertForm.getId();
			sql = "update SYS_EXPERTINFO set NAME=?,SEX=?,AGE=?, TITLE=?, ISPHD=?,DEPT=?,SPECIALTY=?,RESEARCH=?,PHONE=?,EMAIL=?,ADDRESS=?,FACULTY=? ,OTHERONE=?,OTHERTWO=? where ID=?";
			params = new String[]{expertName, sex, age, title, isPHD, dept, specialty, research, phone, email, address, faculty,other1,other2, id};
			sqlAddr="update TB_CONTACT set LOGINNAME=?,CONNAME=?,CONADDR=? where ID=?";
			addrParams = new String[]{mark, expertName, email, addrID};
		}
		boolean result = dbTool.insertItem(sql, params);
		boolean resuatAddr=dbTool.insertItem(sqlAddr, addrParams);
		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result&&resuatAddr)
		{
			json.put("statusCode", 200);
			json.put("message", "保存成功！");
			json.put("callbackType", "closeCurrent");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", "保存失败！");
		}
		out.write(json.toString());
		out.flush();
		out.close();
		
		return null;
		
	}
	/**
	 * 编辑用户信息，跳转
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws IOException
	 */
	public ActionForward edit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");	
		
		ConfigExpertForm configExpertForm = (ConfigExpertForm)form;
		ContactBean contactBean = new ContactBean();
		String id = request.getParameter("uid");
		DBTools dbTools = new DBTools();
		String sql = "select * from SYS_EXPERTINFO where ID=?";
		ExpertInfo expertInfo = dbTools.queryExpertInfo(sql, new String[]{id});
		ArrayList result = new ArrayList();
		if(expertInfo!=null)
		{
			result.add(expertInfo);
			configExpertForm.setRecordNotFind("false");
			configExpertForm.setRecordList(result);
			String addrName=expertInfo.getName();
			request.setAttribute("eSex",expertInfo.getSex());
			request.setAttribute("isPHD",expertInfo.getIsPHD());
			String sqlAddr="select * from TB_CONTACT where CONNAME=? and  LOGINNAME='expert'";
			contactBean=dbTools.queryAddrBean(sqlAddr, new String[]{addrName});
			if(contactBean != null)
			{
				request.setAttribute("addrID", contactBean.getId());
			}
			
			return mapping.findForward("edit");
		}
		else
		{
			configExpertForm.setRecordNotFind("true");
			return mapping.findForward("initError");
		}
	}
}