/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.wsjb;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-17-2013
 * 
 * XDoclet definition:
 * @struts.form name="wsjbManageForm"
 */
public class WsjbManageForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String id;
	private String reportName;
	private String jbBeginTime;
	private String jbEndTime;
	private String beReportName;
	private String wsjbreportReason;
	
	public String getWsjbreportReason() {
		return wsjbreportReason;
	}

	public void setWsjbreportReason(String wsjbreportReason) {
		this.wsjbreportReason = wsjbreportReason;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	public String getBeReportName() {
		return beReportName;
	}

	public void setBeReportName(String beReportName) {
		this.beReportName = beReportName;
	}

	private String recordNotFind = "false";
	private List recordList = null;
	public String getJbBeginTime() {
		return jbBeginTime;
	}

	public void setJbBeginTime(String jbBeginTime) {
		this.jbBeginTime = jbBeginTime;
	}

	public String getJbEndTime() {
		return jbEndTime;
	}

	public void setJbEndTime(String jbEndTime) {
		this.jbEndTime = jbEndTime;
	}

	public String getReportName() {
		return reportName;
	}

	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	public String getRecordNotFind() {
		return recordNotFind;
	}

	public void setRecordNotFind(String recordNotFind) {
		this.recordNotFind = recordNotFind;
	}

	public List getRecordList() {
		return recordList;
	}

	public void setRecordList(List recordList) {
		this.recordList = recordList;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}