/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.wsjb;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.net.URLConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONObject;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.whu.tools.CheckPage;
import com.whu.tools.DBTools;
import com.whu.tools.DebugLog;
import com.whu.tools.ExcelTools;
import com.whu.tools.SystemConstant;
import com.whu.tools.crypto.AESCrypto;
import com.whu.web.common.SystemShare;
import com.whu.web.event.BeReportBean;
import com.whu.web.event.EventBean;
import com.whu.web.eventbean.SjybdBean;
import com.whu.web.log.LogBean;

/** 
 * MyEclipse Struts
 * Creation date: 12-17-2013
 * 
 * XDoclet definition:
 * @struts.action path="/wsjbManageAction" name="wsjbManageForm" parameter="method" scope="request" validate="true"
 */
public class WsjbManageAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private static List<String> orderFields =  Arrays.asList(new String[]{"SERIALNUM","a.STATUS","a.REPORTTIME","a.TIME"});
	private static String caseMergeID = "0";
	/**
	 * 初始化网上举报信息列表
	 */
	public ActionForward init(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		WsjbManageForm wsjbManageForm = (WsjbManageForm) form;
		CheckPage pageBean = new CheckPage();
		int queryPageNo = 1;// 
		int rowsPerPage = 20;// 
		pageBean.setRowsPerPage(rowsPerPage);
		pageBean.setQueryPageNo(queryPageNo);
		String sql = "select a.ID,a.REPORTID,a.REPORTNAME,a.BEREPORTNAME,a.BEDEPT,a.JBSY2,a.TIME,a.REPORTIP from TB_REPORTINFO a where a.ISRECV = '0' order by ID desc";
		String[] params = new String[0];
		request.getSession().setAttribute("queryWsjbSql", sql);
		request.getSession().setAttribute("queryWsjbParams", params);
		pageBean.setQuerySql(sql);
		pageBean.setParams(params);
		WsjbDBTools db = new WsjbDBTools();
		ResultSet rs = db.queryRs(queryPageNo, pageBean, rowsPerPage);
		ArrayList result = db.queryWsjbList(rs, rowsPerPage);
		if(result.size() > 0)
		{
			wsjbManageForm.setRecordNotFind("false");
			wsjbManageForm.setRecordList(result);
			SystemShare.SplitPageFun(request, pageBean, 1);
		}
		else
		{
			wsjbManageForm.setRecordNotFind("true");
			SystemShare.SplitPageFun(request, pageBean, 0);
		}
		return mapping.findForward("init");
	}
	
	/**
	 * 查询和分页
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward queryMsg(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");	
		WsjbManageForm wsjbManageForm = (WsjbManageForm) form;
		String operation = request.getParameter("operation");
		//排序控制
		String orderField = request.getParameter("orderField");//排序的字段(数据库字段名称)
		String orderDirection = request.getParameter("orderDirection");//排序的方向，desc,asc

		CheckPage pageBean = new CheckPage();
		String sql = "";
		String[] params = new String[0];
		int queryPageNo = 1;
		int rowsPerPage = 20;
		pageBean.setRowsPerPage(rowsPerPage);

		if (operation.equalsIgnoreCase("search") || operation.equalsIgnoreCase("select")) {
			String IsNi = request.getParameter("isNi");
			
			String reportName = wsjbManageForm.getReportName();
			String beReportName = wsjbManageForm.getBeReportName();
			String jbBeginTime = wsjbManageForm.getJbBeginTime();
			String jbEndTime = wsjbManageForm.getJbEndTime();
			String temp = "";
			ArrayList<String> paramList = new ArrayList<String>();
			AESCrypto aes = new AESCrypto();
			String key = "TB_REPORTINFO";
			//String test=SystemShare.getHexString(aes.createEncryptor("匿名举报", key));
			//System.out.println(test);
			if(IsNi != null)//匿名举报，勾选了复选框
			{
				//temp += " and 1=dbo.compare_image1(a.REPORTNAME,0x" + SystemShare.getHexString(aes.createEncryptor("匿名举报", key)) + ") ";
				temp += " and hex(a.REPORTNAME) = '"+ SystemShare.getHexString(aes.createEncryptor("匿名举报", key))+"'";
			}
			else if(reportName != null && !reportName.equals(""))
			{
				//调用sqlserver自定义函数比较加密后的数据是否相等。
				//compare_image1为比较函数，共两个参数，第一个为字段名称，第二个字段为加密后的数据（注意加密后为字节数据，需要转换为十六进制字符串，另在前面加上0x）
				//temp += " and 1=dbo.compare_image1(a.REPORTNAME,0x" + SystemShare.getHexString(aes.createEncryptor(reportName, key)) + ") ";
				temp += " and hex(a.REPORTNAME) = '" + SystemShare.getHexString(aes.createEncryptor(reportName, key))+"'";
			}
			if(beReportName != null && !beReportName.equals(""))
			{
				//temp += " and 1=dbo.compare_image1(a.BEREPORTNAME,0x" + SystemShare.getHexString(aes.createEncryptor(beReportName, key)) + ") ";
				temp += " and hex(a.BEREPORTNAME) = '" + SystemShare.getHexString(aes.createEncryptor(beReportName, key))+"'";
			}
			if(jbBeginTime != null && !jbBeginTime.equals(""))
			{
				temp += " and a.TIME >= ?";
				paramList.add(jbBeginTime);
			}
			if(jbEndTime != null && !jbEndTime.equals(""))
			{
				temp += " and a.TIME <= ?";
				paramList.add(jbEndTime);
			}
			params = paramList.toArray(new String[0]);
			sql = "select a.ID,a.REPORTID,a.REPORTNAME,a.BEREPORTNAME,a.BEDEPT,a.JBSY2,a.TIME,a.REPORTIP from TB_REPORTINFO a where a.ISRECV = '0' " + temp + "  order by ID desc";
			request.getSession().setAttribute("queryWsjbSql", sql);
			request.getSession().setAttribute("queryWsjbParams", params);
		}
		
		else if(operation.equalsIgnoreCase("changePage")){
			sql = (String)request.getSession().getAttribute("queryWsjbSql");
			params = (String[])request.getSession().getAttribute("queryWsjbParams");
			if(orderField != null && orderFields.contains(orderField) && orderDirection != null && orderDirection.matches("asc|desc"))
			{
				sql = sql.substring(0, sql.indexOf("order"));
				sql += " order by " + orderField + " " + orderDirection;
			}
			if (request.getParameter("pageNum") != null && request.getParameter("pageNum") != "") {
				queryPageNo = Integer.parseInt(request.getParameter("pageNum"));
			}
		}
		pageBean.setQuerySql(sql);
		pageBean.setParams(params);
		pageBean.setQueryPageNo(queryPageNo);
		WsjbDBTools db = new WsjbDBTools();
		ResultSet rs = db.queryRs(queryPageNo, pageBean, rowsPerPage);
		ArrayList result = db.queryWsjbList(rs, rowsPerPage);
		if(result.size() > 0)
		{
			wsjbManageForm.setRecordNotFind("false");
			wsjbManageForm.setRecordList(result);
			SystemShare.SplitPageFun(request, pageBean, 1);
		}
		else
		{
			wsjbManageForm.setRecordNotFind("true");
			SystemShare.SplitPageFun(request, pageBean, 0);
		}
		return mapping.findForward("init");
	}
	/**
	 * 删除网上举报信息
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		
		String ids = request.getParameter("ids");
		WsjbDBTools dbTool = new WsjbDBTools();
		boolean result = true;
		if(ids == null || ids.equals(""))
		{
			String id = request.getParameter("id");
			result = dbTool.deleteItem(id, "TB_REPORTINFO");
		}
		else
		{
			String[] arrID = ids.split(",");
			result = dbTool.deleteItems(arrID, "TB_REPORTINFO");
		}
		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result)
		{
			json.put("statusCode", 200);
			json.put("message", "删除成功！");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", "删除失败！");
		}
		out.write(json.toString());
		out.flush();
		out.close();
		
		return null;
	}
	/**
	 * 不受理在网上举报的案件，将案件入库，但是状态设置为“未受理”
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward unrecv(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		String id = request.getParameter("id");
		RESULTSET rs = GyMethod(id,  SystemConstant.SS_UNRECVEVENT, request);
		boolean result = rs.getFlag();

		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result)
		{
			json.put("statusCode", 200);
			json.put("message", "不受理案件成功！");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", "不受理案件失败！");
		}
		out.write(json.toString());
		out.flush();
		out.close();
		
		return null;
	}
	/**
	 * 受理或者不受理案件的公用方法
	 * @param id
	 * @param status
	 * @param request
	 * @return
	 */
	public  RESULTSET GyMethod(String id, String status, HttpServletRequest request)
	{
		RESULTSET rs = new RESULTSET();
		String createName = (String)request.getSession().getAttribute("UserName");
		boolean result = false;
		String sql = "";
		WsjbDBTools dbTool = new WsjbDBTools();
		WsjbInfo wsjbInfo = dbTool.QueryWsjbInfo(id);
		sql = "select * from TB_BEREPORTPE where REPORTID=?";
		BeReportBean brb = null;
		DBTools db = new DBTools(); 
		ArrayList beReportList = dbTool.queryBeReport(sql,new String[]{wsjbInfo.getReportID()});
		try {
			//插入被举报人信息
			result = db.insertBeReport(beReportList);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		/*
		DBTools db = new DBTools(); 
		ArrayList list = new ArrayList();
		BeReportBean brb = new BeReportBean();
		brb.setReportID(wsjbInfo.getReportID());
		brb.setBeName(wsjbInfo.getBeReportName());
		brb.setBePosition(wsjbInfo.getBePosition());
		brb.setBeTelPhone(wsjbInfo.getBePhone());
		brb.setBeDept(wsjbInfo.getBeDept());
		list.add(brb);
		try {
			//插入被举报人信息
			result = db.insertBeReport(list);
		} catch (SQLException e) {
			
			e.printStackTrace();
		}*/
		String createTime = SystemShare.GetNowTime("yyyy-MM-dd");
		
		EventBean eb = new EventBean();
		eb.setReportID(wsjbInfo.getReportID());
		//受理的案件自动分配编号，不受理的案件不分配编号
		if(status.equals(SystemConstant.SS_RECVEVENT))
		{
			//sql = "select SERIALNUM from TB_REPORTINFO where STATUS<>? and ISDIGIT=1 order by ID desc limit 1";
			sql = "select SERIALNUM from TB_REPORTINFO where STATUS<>? and ISDIGIT=1 order by SERIALNUM desc limit 1";
			eb.setSerialNum(SystemShare.GetSerialNum(sql, new String[]{SystemConstant.SS_UNRECVEVENT}));
			eb.setIsDigit(isDigit(eb.getSerialNum()));
			rs.setSerialNum(eb.getSerialNum());
		}
		else
		{
			eb.setSerialNum("");
		}
		eb.setReportName(wsjbInfo.getReportName());
		eb.setDept(wsjbInfo.getDept());
		eb.setGdPhone(wsjbInfo.getGdPhone());
		eb.setTelPhone(wsjbInfo.getTelPhone());
		eb.setMailAddress(wsjbInfo.getMailAddres());
		eb.setReportTime(wsjbInfo.getTime());
		eb.setReportType("网络举报");
		eb.setCreateTime(createTime);
		eb.setCreateName(createName);
		//eb.setReportReason(wsjbInfo.getJbsy1() + "---" + wsjbInfo.getJbsy2());
		eb.setReportReason(wsjbInfo.getJbsy2());
		eb.setReportContent(wsjbInfo.getDetail());
		eb.setStatus(status);
		eb.setBeReportName(wsjbInfo.getBeReportName());
		eb.setIsDelete("0");
		eb.setIsNI(wsjbInfo.getIsNi());
		eb.setSearchID(wsjbInfo.getSearchID());
		
		//将举报者上传的附件转存到系统附件目录下
		String attachPath = wsjbInfo.getAttachPath();
		if(!attachPath.equals("无"))
		{
			String fileName = attachPath.substring(attachPath.lastIndexOf("/") + 1);
			String filePath = request.getSession().getServletContext().getRealPath("/")+"/attachment/";
			String path = filePath + wsjbInfo.getReportID() + "/";
			String serverPath = SystemConstant.GetServerPath() + "/" + "attachment" + "/" + wsjbInfo.getReportID() + "/" + fileName;
			//result = SystemShare.IOCopyFile(attachPath, path, createName);
			//System.out.println(attachPath);
			//System.out.println(fileName);
			//System.out.println(filePath);
			//System.out.println(path);
			//System.out.println(serverPath);
			result = SystemShare.DownloadFile(attachPath, path, fileName, serverPath, createName);
			if(result)
			{
				eb.setAccessory(wsjbInfo.getReportID() + "/" + fileName);
			}
		}
		//插入举报信息10
		result = db.InsertReportInfo(eb);
		
		if(result)
		{
			LogBean lb = new LogBean();
			if(status.equals(SystemConstant.SS_RECVEVENT))
			{
			String describe = wsjbInfo.getTime() + "," + wsjbInfo.getReportName() + "在监督委员会门户网站在线举报" + wsjbInfo.getBeReportName() + ",举报事由为：" + wsjbInfo.getJbsy2();
			db.InsertHandleProcess(wsjbInfo.getReportID(), wsjbInfo.getReportName(), SystemConstant.HP_REPORT, SystemConstant.SS_RECVEVENT, SystemConstant.LCT_JB, describe);
			
			describe = createTime + "," + createName + "接受录入在线举报," + wsjbInfo.getReportName() + "举报" + wsjbInfo.getBeReportName();
			//插入处理过程到数据库中
			db.InsertHandleProcess(wsjbInfo.getReportID(), createName, SystemConstant.HP_RECVEVENT, SystemConstant.SS_RECVEVENT, SystemConstant.LCT_SLJB, describe);
			
			//更新前台数据库中事件的接收状态
			sql = "update TB_REPORTINFO set ISRECV='1' where ID=?";
			result = dbTool.UpdateItem(sql, new String[]{id});
			//更新反馈内容
			String sqlStr = "insert into TB_FKINFO(SEARCHID, FKCONTENT,FKTIME) values(?, ?, ?)" ;
			String[] params = new String[]{wsjbInfo.getSearchID(), SystemConstant.FK_RECVEVENT, createTime};
			result = dbTool.UpdateItem(sqlStr, params);
			dbTool.closeConnection();
			
			lb.setOperator(createName);
			lb.setLogType(SystemConstant.LOG_RECV);
			lb.setIpAddr(request.getRemoteAddr());
			lb.setDetail("接收网上举报事件，事件编号为：" + wsjbInfo.getReportID());
			result = db.insertLogInfo(lb);
			}
			else
			{
				String describe = wsjbInfo.getTime() + "," + wsjbInfo.getReportName() + "在监督委员会门户网站在线举报" + wsjbInfo.getBeReportName() + ",举报事由为：" + wsjbInfo.getJbsy2();
				db.InsertHandleProcess(wsjbInfo.getReportID(), wsjbInfo.getReportName(), SystemConstant.HP_REPORT, SystemConstant.SS_UNRECVEVENT, SystemConstant.LCT_JB, describe);
				
				describe = createTime + "," + createName + "不接受录入在线举报," + wsjbInfo.getReportName() + "举报" + wsjbInfo.getBeReportName();
				//插入处理过程到数据库中
				db.InsertHandleProcess(wsjbInfo.getReportID(), createName, SystemConstant.HP_UNRECVEVENT, SystemConstant.SS_UNRECVEVENT, SystemConstant.LCT_UNSLJB, describe);
				
				//更新前台数据库中事件的接收状态
				sql = "update TB_REPORTINFO set ISRECV='1' where ID=?";
				result = dbTool.UpdateItem(sql, new String[]{id});
				//更新反馈内容
				String sqlStr = "insert into TB_FKINFO(SEARCHID, FKCONTENT,FKTIME) values(?, ?, ?)" ;
				String[] params = new String[]{wsjbInfo.getSearchID(), SystemConstant.FK_UNRECVEVENT, createTime};
				result = dbTool.UpdateItem(sqlStr, params);
				dbTool.closeConnection();
				lb.setOperator(createName);
				lb.setLogType(SystemConstant.LOG_UNRECV);
				lb.setIpAddr(request.getRemoteAddr());
				lb.setDetail("不接收该网上举报事件。");
				result = db.insertLogInfo(lb);
			}
		}
		rs.setFlag(result);
		return rs;
	}
	/**
	 * 接收网上举报信息到管理平台
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward recv(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		String id = request.getParameter("id");
		RESULTSET rs = GyMethod(id,  SystemConstant.SS_RECVEVENT, request);
		boolean result = rs.getFlag();
		
		request.getSession().setAttribute("yuebandanID", id);

		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result)
		{
			json.put("statusCode", 200);
			json.put("message", "接收网上举报成功！");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", "接收网上举报失败！");
		}
		out.write(json.toString());
		out.flush();
		out.close();
		return null;
		
//		if(result)
//		{
//			return mapping.findForward("recvsucceed");
//		}elsel
//		{
//			return mapping.findForward("recvfailed");
//		}
	}
	
	public ActionForward recvNew(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		WsjbManageForm wsjbManageForm = (WsjbManageForm)form;
		String reportID = request.getParameter("id");
		WsjbDBTools dbTool = new WsjbDBTools();
		WsjbInfo wsjbInfo = dbTool.QueryWsjbInfo(reportID);
		String maxSerialNum = "";
			//recv case
			RESULTSET rs = GyMethod(reportID,  SystemConstant.SS_RECVEVENT, request);
			boolean flag = rs.getFlag();
			
			if(flag)
			{
				maxSerialNum = rs.getSerialNum();
			}
			else
			{
				return mapping.findForward("recvfailed");
			}
		
		
		//create YBD
		String sql = "select * from TB_SJYBDINFO where REPORTID=?";
		DBTools dbTools = new DBTools();
		SjybdBean sb = dbTools.querySJYBD(sql, new String[]{wsjbInfo.getReportID()});
		ArrayList result = new ArrayList();
		if(sb==null)//生成阅办单信息还未保存，从TB_REPORTINFO提取相关信息保存到TB_SJYBDINFO
		{
			sb = new SjybdBean();
			sb.setReportID(wsjbInfo.getReportID());
			sb.setSerialNum(maxSerialNum);
			sb.setRecvTime(wsjbInfo.getTime());
			sb.setComeName(wsjbInfo.getReportName());
		}
		result.add(sb);
		wsjbManageForm.setRecordList(result);
		return mapping.findForward("createybd");
	}
	/**
	 * 查看网上举报详细信息
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward detail(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		WsjbManageForm wsjbManageForm = (WsjbManageForm) form;
		String id = request.getParameter("id");
		WsjbDBTools dbTool = new WsjbDBTools();
		WsjbInfo wsjbInfo = dbTool.QueryWsjbInfo(id);
		
		/*****coding test*******/
		String sql = "select * from TB_BEREPORTPE where REPORTID=?";
		ArrayList beReportList = dbTool.queryBeReport(sql, new String[]{wsjbInfo.getReportID()});
		if(beReportList != null && beReportList.size() > 0)
		{
			wsjbInfo.setBeReportList(beReportList);
		}
		/*****coding test*******/
		ArrayList list = new ArrayList();
		list.add(wsjbInfo);
		wsjbManageForm.setRecordNotFind("false");
		wsjbManageForm.setRecordList(list);
		
		return mapping.findForward("detail");
	}
	/**
	 * 导出列表
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward export(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		WsjbDBTools db = new WsjbDBTools();
		String sql = (String)request.getSession().getAttribute("queryWsjbSql");
		String[] params = (String[])request.getSession().getAttribute("queryWsjbParams");
		try
		{
			String fname = "event";
			OutputStream os = response.getOutputStream();
			response.reset();
			response.setHeader("Content-disposition", "attachment;filename=" + fname + ".xls");
			response.setContentType("application/msexcel");
			ResultSet rs = db.queryRsList(sql, params);
			rs.last();
			int length = rs.getRow();
			rs.beforeFirst();
			ArrayList result = db.queryWsjbList(rs, length);
			ExcelTools et = new ExcelTools();
			//et.createSheet(rs, os);
			String sheetName = "网上举报汇总表";
			ArrayList titleList = new ArrayList();
			titleList.add("编号");
			titleList.add("举报人姓名");
			titleList.add("被举报人姓名");
			titleList.add("举报时间");
			titleList.add("举报事由");
			titleList.add("状态");
			et.createEventSheet(result, os, sheetName, 1, titleList);
			rs.close();
		}
		catch(Exception e)
		{
			DebugLog.WriteDebug(e);
		}
		return null;
	}
	
	/**
	 * 编辑
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward edit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		WsjbManageForm wsjbManageForm = (WsjbManageForm) form;
		String id = wsjbManageForm.getId();
		String wsjbreportReason = wsjbManageForm.getWsjbreportReason();
		WsjbDBTools dbTool = new WsjbDBTools();
		boolean result = true;
		String sql = "update TB_REPORTINFO set JBSY2=? where ID=?";
		result = dbTool.UpdateItem(sql, new String[]{wsjbreportReason,id});
		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result)
		{
			json.put("statusCode", 200);
			json.put("message", "编辑成功！");
			json.put("navTabId", "wsjb");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", "编辑失败！");
		}
		out.write(json.toString());
		out.flush();
		out.close();
		
		return null;
	}
	
	/**
	 * 打印事件详情
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws UnsupportedEncodingException
	 */
	public ActionForward print(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws UnsupportedEncodingException {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		String id = request.getParameter("id");
		
		WsjbDBTools dbTool = new WsjbDBTools();
		WsjbInfo wsjbInfo = dbTool.QueryWsjbInfo(id);
		
		String sql = "select * from TB_BEREPORTPE where REPORTID=?";
		ArrayList beReportList = dbTool.queryBeReport(sql, new String[]{wsjbInfo.getReportID()});
		if(beReportList != null && beReportList.size() > 0)
		{
			wsjbInfo.setBeReportList(beReportList);
		}
		
		String templatePath = "web/template/sjxq" + String.valueOf(beReportList.size()) + ".doc";
		
		request.setAttribute("WsjbInfo", wsjbInfo);
		request.setAttribute("ReportID", id);
		request.setAttribute("ServerPath", SystemConstant.GetServerPath());
		request.setAttribute("templatePath", templatePath);
		
		
		return mapping.findForward("printEvent_recv");
	}
	
	/**
	 * 案件合并
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward caseMerge(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		WsjbManageForm wsjbManageForm = (WsjbManageForm)form;
		String id = request.getParameter("id");
		request.getSession().setAttribute("caseMergeID", id);
	
		
		return mapping.findForward("caseMerge");
	}
	
	/**
	 * 合并
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward merge(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		WsjbManageForm wsjbManageForm = (WsjbManageForm) form;
		String caseSerialNum = wsjbManageForm.getId();
		MergeDBTools dbtool = new MergeDBTools();
		String reportID1 = dbtool.queryTB(caseSerialNum);
		String mID =(String) request.getSession().getAttribute("caseMergeID");
		if(reportID1 != "/00000" && caseSerialNum != null){
			GyMethod(mID, SystemConstant.SS_RECVEVENT,request);
			WsjbDBTools dbtool1 = new WsjbDBTools();
			String reportID = dbtool1.queryReportID(mID);
			MergeDBTools dbtool2 = new MergeDBTools();
			dbtool2.updateDB(reportID, reportID1, caseSerialNum);
			response.getWriter().print("true");
		}else{
			response.getWriter().print("false");
			
		}
		return null;
	}
	
	public ActionForward changeSerialnum(ActionMapping mapping, ActionForm form,                                   //CP.01  the whole function
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		WsjbManageForm wsjbManageForm = (WsjbManageForm) form;
		String Userialnum = request.getParameter("USnum"); //user define serialnum
		String reportid = request.getParameter("RID");
		//System.out.println(Userialnum + "\t"+reportid);
		DefSerialnumDBTools dbtool = new DefSerialnumDBTools();
		boolean change = dbtool.changeSerialnum(Userialnum, reportid);
		if(change == true) response.getWriter().print("true");
		else response.getWriter().print("false");
		
		return null;
	}
	
	private class RESULTSET{
		private boolean flag = false;
		private String serialNum = "";
		public boolean getFlag() {
			return flag;
		}
		public void setFlag(boolean flag) {
			this.flag = flag;
		}
		public String getSerialNum() {
			return serialNum;
		}
		public void setSerialNum(String serialNum) {
			this.serialNum = serialNum;
		}
	}
	
	private int isDigit(String str)
	{
		for(int i = 0;i<str.length();i++)
		{
			if(!Character.isDigit(str.charAt(i)))
				return 0;
		}
		return 1;
	}
}