/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.user;

import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.whu.tools.CheckPage;
import com.whu.tools.DBTools;
import net.sf.json.JSONArray;

/** 
 * MyEclipse Struts
 * Creation date: 08-07-2013
 * 
 * XDoclet definition:
 * @struts.action path="/gyUserListAction" name="gyUserListForm" parameter="method" scope="request" validate="true"
 */
public class GyUserListAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward init(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GyUserListForm gyUserListForm = (GyUserListForm) form;// TODO Auto-generated method stub
		 
		// This method hasn't been used, what does it work?
		
		CheckPage pageBean = new CheckPage();
		int queryPageNo = 1;// �����ҳ��
		int rowsPerPage = 20;// ÿҳ������
		pageBean.setRowsPerPage(rowsPerPage);
		if (request.getParameter("queryPageNo") != null) {
			queryPageNo = Integer.parseInt(request.getParameter("queryPageNo"));
		}
		pageBean.setQueryPageNo(queryPageNo);
		String sql = "select a.ID,a.USERNAME,b.ZZNAME from SYS_USER a, SYS_ZZINFO where a.ZZID=b.ZZNAME";
		String[] params = new String[0];
		request.getSession().setAttribute("queryGYUserSql", sql);
		request.getSession().setAttribute("queryGYUserParams", params);
		pageBean.setQuerySql(sql);
		pageBean.setParams(params);
		DBTools db = new DBTools();
		ResultSet rs = db.queryRs(queryPageNo, pageBean, rowsPerPage);
		ArrayList result = db.queryGYUserList(rs, rowsPerPage);
		if(result.size() > 0)
		{
			gyUserListForm.setRecordNotFind("false");
			gyUserListForm.setRecordList(result);
			
			int totalRows = pageBean.getTotalRows();
			int pagecount = pageBean.getTotalPage();// �õ���ҳ��
			int currentPage = pageBean.getQueryPageNo();// �õ���ǰҳ
			request.setAttribute("pageNum",String.valueOf(currentPage));
			request.setAttribute("totalRows",String.valueOf(totalRows));
			request.setAttribute("pageCount",String.valueOf(pagecount));
		}
		else
		{
			gyUserListForm.setRecordNotFind("true");
			request.setAttribute("pageNum",String.valueOf(0));
			request.setAttribute("totalRows",String.valueOf(0));
			request.setAttribute("pageCount",String.valueOf(0));
		}
		return mapping.findForward("init");
	}
	
}