/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.credit;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONObject;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.whu.tools.DBTools;
import com.whu.web.credit.InstituteInfo;

/** 
 * MyEclipse Struts
 * Creation date: 12-05-2014
 * 
 * XDoclet definition:
 * @struts.action path="/configPunishAction" name="configPunishForm" parameter="method" scope="request" validate="true"
 */
public class ConfigPunishAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	public ActionForward save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");	
		ConfigPunishForm configPunishForm = (ConfigPunishForm)form;
		String operation = request.getParameter("operation");
		String codename = configPunishForm.getCodename();
		String code = configPunishForm.getCode();
		String caption = configPunishForm.getCaption();
		String remark = configPunishForm.getRemark();
		String year = configPunishForm.getYear();
		String rate = configPunishForm.getRate();
		
		String sql_dic = "";
		String[] dicParams = null;
		String[] rateParams = null;
		String sql_rate = "";
		DBTools dbTool = new DBTools();
		if(operation.equals("new")) {
			sql_dic = "insert into SYS_DATA_DIC(CODENAME,CODE,CAPTION,REMARK) values(?, ?, ?, ?)";
			dicParams = new String[]{codename, code, caption, remark};
			sql_rate = "insert into SYS_CLJD_RATE(CODE,YEAR,RATE) values(?, ?, ?)";
			rateParams = new String[]{code, year, rate};
		} 
		else if(operation.equals("edit")) {
			String id = configPunishForm.getId();
			sql_dic = "update SYS_DATA_DIC set CODENAME=?, CODE=?, CAPTION=?, REMARK=? where ID=?";
			dicParams = new String[]{codename, code, caption, remark, id};
			sql_rate = "update SYS_CLJD_RATE set YEAR=?, RATE=? where CODE=?";
			rateParams = new String[]{year, rate, code};
		}
		boolean result = dbTool.insertItem(sql_dic, dicParams) && dbTool.insertItem(sql_rate, rateParams);
		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result)
		{
			json.put("statusCode", 200);
			json.put("message", "保存成功！");
			json.put("callbackType", "closeCurrent");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", "保存失败！");
		}
		out.write(json.toString());
		out.flush();
		out.close();
		
		return null;
		
	}
	/**
	 * 编辑信息，跳转
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws IOException
	 */
	public ActionForward edit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");	
		
		ConfigPunishForm configPunishForm = (ConfigPunishForm)form;
		String id = request.getParameter("uid");
		DBTools dbTools = new DBTools();
		
		PunishBean punishBean = dbTools.queryPunishConfig(id);
		ArrayList result = new ArrayList();
		if(punishBean != null){
			result.add(punishBean);
			configPunishForm.setRecordNotFind("false");
			configPunishForm.setRecordList(result);
			
			return mapping.findForward("edit");
			
		} else {
			configPunishForm.setRecordNotFind("true");
			return mapping.findForward("initError");
		}		
	}
}