/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.credit;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-02-2014
 * 
 * XDoclet definition:
 * @struts.form name="configMiscountForm"
 */
public class ConfigMiscountForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** id property */
	private String id;

	/** detail property */
	private String detail;

	/** time property */
	private String time;

	/** title property */
	private String title;

	/** individual property */
	private String individual;

	/** institute property */
	private String institute;

	/** punish property */
	private String punish;

	/** mistype property */
	private String mistype;

	/** reportId property */
	private String reportId;

	
	
	private String recordNotFind = "false";
	private List recordList = null;
	public String getRecordNotFind() {
		return recordNotFind;
	}

	public void setRecordNotFind(String recordNotFind) {
		this.recordNotFind = recordNotFind;
	}

	public List getRecordList() {
		return recordList;
	}

	public void setRecordList(List recordList) {
		this.recordList = recordList;
	}
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the detail.
	 * @return String
	 */
	public String getDetail() {
		return detail;
	}

	/** 
	 * Set the detail.
	 * @param detail The detail to set
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/** 
	 * Returns the time.
	 * @return String
	 */
	public String getTime() {
		return time;
	}

	/** 
	 * Set the time.
	 * @param time The time to set
	 */
	public void setTime(String time) {
		this.time = time;
	}

	/** 
	 * Returns the title.
	 * @return String
	 */
	public String getTitle() {
		return title;
	}

	/** 
	 * Set the title.
	 * @param title The title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/** 
	 * Returns the individual.
	 * @return String
	 */
	public String getIndividual() {
		return individual;
	}

	/** 
	 * Set the individual.
	 * @param individual The individual to set
	 */
	public void setIndividual(String individual) {
		this.individual = individual;
	}

	/** 
	 * Returns the institute.
	 * @return String
	 */
	public String getInstitute() {
		return institute;
	}

	/** 
	 * Set the institute.
	 * @param institute The institute to set
	 */
	public void setInstitute(String institute) {
		this.institute = institute;
	}

	/** 
	 * Returns the punish.
	 * @return String
	 */
	public String getPunish() {
		return punish;
	}

	/** 
	 * Set the punish.
	 * @param punish The punish to set
	 */
	public void setPunish(String punish) {
		this.punish = punish;
	}

	/** 
	 * Returns the mistype.
	 * @return String
	 */
	public String getMistype() {
		return mistype;
	}

	/** 
	 * Set the mistype.
	 * @param mistype The mistype to set
	 */
	public void setMistype(String mistype) {
		this.mistype = mistype;
	}

	/** 
	 * Returns the reportId.
	 * @return String
	 */
	public String getReportId() {
		return reportId;
	}

	/** 
	 * Set the reportId.
	 * @param reportId The reportId to set
	 */
	public void setReportId(String reportId) {
		this.reportId = reportId;
	}
}