/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.credit;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONObject;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.whu.tools.DBTools;
import com.whu.web.credit.IndividualInfo;

/** 
 * MyEclipse Struts
 * Creation date: 12-01-2014
 * 
 * XDoclet definition:
 * @struts.action path="/configIndividualAction" name="configIndividualForm" parameter="method" scope="request" validate="true"
 */
public class ConfigIndividualAction extends DispatchAction {
	public ActionForward save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");	
		ConfigIndividualForm configIndividualForm = (ConfigIndividualForm)form;
		String operation = request.getParameter("operation");
		String sex = configIndividualForm.getSex();
		String pid = configIndividualForm.getPid();
		String name = configIndividualForm.getName();
		String institute = configIndividualForm.getInstitute();
		String specialty = configIndividualForm.getSpecialty();
		String phone = configIndividualForm.getPhone();
		String address = configIndividualForm.getAddress();
		String email = configIndividualForm.getEmail();
		String isExpert = configIndividualForm.getIsExpert();
		String title = configIndividualForm.getTitle();
		
		DBTools dbTool = new DBTools();
		String sql = "";
		String[] params = new String[0];
		if(operation.equals("new")) {
			sql = "insert into SYS_INDIVIDUAL_INFO(NAME,SEX,PID,INSTITUTE,SPECIALTY,PHONE,ADDRESS,EMAIL,ISEXPERT,TITLE) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
			params = new String[]{name, sex, pid, institute, specialty, phone, address, email, isExpert, title};
		} 
		else if(operation.equals("edit")) {
			String id = configIndividualForm.getId();
			sql = "update SYS_INDIVIDUAL_INFO set NAME=?, SEX=?, PID=?, INSTITUTE=?, SPECIALTY=?, PHONE=?, ADDRESS=?, EMAIL=?, ISEXPERT=?, TITLE=? where ID=?";
			params = new String[]{name, sex, pid, institute, specialty, phone, address, email, isExpert, title};
		}
		boolean result = dbTool.insertItem(sql, params);
		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result)
		{
			json.put("statusCode", 200);
			json.put("message", "保存成功！");
			json.put("callbackType", "closeCurrent");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", "保存失败！");
		}
		out.write(json.toString());
		out.flush();
		out.close();
		
		return null;
		
	}
	/**
	 * 编辑信息，跳转
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws IOException
	 */
	public ActionForward edit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");	
		
		ConfigIndividualForm configIndividualForm = (ConfigIndividualForm)form;
		String id = request.getParameter("uid");
		DBTools dbTools = new DBTools();
		String sql = "select a.*,b.NAME as INSTNAME from SYS_INDIVIDUAL_INFO a, SYS_INST_INFO b where a.ID=? and a.INSTITUTE=b.CODE";
		IndividualInfo IndividualInfo = dbTools.queryIndividualInfo(sql, new String[]{id});
		ArrayList result = new ArrayList();
		if(IndividualInfo != null){
			result.add(IndividualInfo);
			configIndividualForm.setRecordNotFind("false");
			configIndividualForm.setRecordList(result);
			
			return mapping.findForward("edit");
			
		} else {
			configIndividualForm.setRecordNotFind("true");
			return mapping.findForward("initError");
		}		
	}
}