/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.credit;

import java.util.List;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-05-2014
 * 
 * XDoclet definition:
 * @struts.form name="mistypeManageForm"
 */
public class MistypeManageForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String name;
	private String recordNotFind = "false";
	private List recordList;
	
	public String getName() {
		return name;
	}
	public void setName( String name) {
		this.name = name;
	}
	public String getRecordNotFind() {
		return recordNotFind;
	}
	public void setRecordNotFind( String recordNotFind) {
		this.recordNotFind = recordNotFind;
	}
	public List getRecordList() {
		return recordList;
	}
	public void setRecordList( List recordList) {
		this.recordList = recordList;
	}	
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}