/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.credit;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONArray;
import net.sf.json.JSONObject;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.whu.tools.CheckPage;
import com.whu.tools.DBTools;
import com.whu.web.common.SystemShare;
import com.whu.web.credit.MistypeBean;

/** 
 * MyEclipse Struts
 * Creation date: 12-05-2014
 * 
 * XDoclet definition:
 * @struts.action path="/mistypeManageAction" name="mistypeManageForm" parameter="method" scope="request" validate="true"
 * @struts.action-forward name="init" path="/web/credit/mistypeManage.jsp"
 */
public class MistypeManageAction extends DispatchAction {

	public void initTree(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		MistypeManageForm mistypeManageForm = (MistypeManageForm) form;
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		//type=1 表示正常显示菜单，type=2表示展开所有菜单项，用于选择上级type时的下拉菜单
		String type = request.getParameter("type");
		
		//String sql = "select * from SYS_JBREASON where RSORT='1'";
		String sql = "select * from SYS_JBREASON where RSORT='1' and ISJC='1'";
		if(type.equals("2")) {
			sql = "select * from SYS_JBREASON where RSORT='1' and ISJC='1'";
		}
		DBTools dbTools = new DBTools();
		
        List<String> lstTree = dbTools.queryReasonTree(sql, type);
        //利用Json插件将Array转换成Json格式
        response.getWriter().print(JSONArray.fromObject(lstTree).toString()); 
	}
	/**
	 * 选定一个mistype main，显示
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws IOException
	 */
	public ActionForward init(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		
		MistypeManageForm mistypeManageForm = (MistypeManageForm) form;
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		CheckPage pageBean = new CheckPage();
		int queryPageNo = 1;// 
		int rowsPerPage = 20;// 
		pageBean.setRowsPerPage(rowsPerPage);
		if (request.getParameter("queryPageNo") != null && request.getParameter("queryPageNo") != "") {
			queryPageNo = Integer.parseInt(request.getParameter("queryPageNo"));
		}
		pageBean.setQueryPageNo(queryPageNo);
		
		String sql = "select * from SYS_JBREASON where RSORT='1' and ISJC='1' order by RID asc";
		String[] params = new String[0];
		request.getSession().setAttribute("queryMistypeSql", sql);
		request.getSession().setAttribute("queryMistypeParams", params);
		pageBean.setQuerySql(sql);
		pageBean.setParams(params);
		
		DBTools db = new DBTools();
		ResultSet rs = db.queryRs(queryPageNo, pageBean, rowsPerPage);
		ArrayList result = db.queryMistypeList(rs, rowsPerPage);
		if(result.size() > 0)
		{
			mistypeManageForm.setRecordNotFind("false");
			mistypeManageForm.setRecordList(result);
			
			SystemShare.SplitPageFun(request, pageBean, 1);
		}
		else
		{
			mistypeManageForm.setRecordNotFind("true");
			
			SystemShare.SplitPageFun(request, pageBean, 0);
		}

		request.setAttribute("RID", "0"); // for individual credit factor weight handler show
		return mapping.findForward("init");
	}
	
	
	public ActionForward initAll(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		MistypeManageForm mistypeManageForm = (MistypeManageForm) form;
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		CheckPage pageBean = new CheckPage();
		int queryPageNo = 1;// 
		int rowsPerPage = 20;// 
		pageBean.setRowsPerPage(rowsPerPage);
		if (request.getParameter("queryPageNo") != null && request.getParameter("queryPageNo") != "") {
			queryPageNo = Integer.parseInt(request.getParameter("queryPageNo"));
		}
		pageBean.setQueryPageNo(queryPageNo);
		
		String sql = "select a.*,b.RNAME as PNAME from SYS_JBREASON a, SYS_JBREASON b where a.RID='1' and a.PRID=b.RID order by RID asc";
		String[] params = new String[0];
		request.getSession().setAttribute("queryMistypeSql", sql);
		request.getSession().setAttribute("queryMistypeParams", params);
		pageBean.setQuerySql(sql);
		pageBean.setParams(params);
		
		DBTools db = new DBTools();
		ResultSet rs = db.queryRs(queryPageNo, pageBean, rowsPerPage);
		ArrayList result = db.queryMistypeList(rs, rowsPerPage);
		if(result.size() > 0)
		{
			mistypeManageForm.setRecordNotFind("false");
			mistypeManageForm.setRecordList(result);
			
			SystemShare.SplitPageFun(request, pageBean, 1);
		}
		else
		{
			mistypeManageForm.setRecordNotFind("true");
			
			SystemShare.SplitPageFun(request, pageBean, 0);
		}

		request.setAttribute("RID", "0"); // for individual credit factor weight handler show
		return mapping.findForward("init");
	}
	
	public ActionForward queryMsg(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");	
		MistypeManageForm mistypeManageForm = (MistypeManageForm) form;
		String operation = request.getParameter("operation");

		CheckPage pageBean = new CheckPage();
		String sql = "";
		String[] params = new String[0];
		int queryPageNo = 1;
		int rowsPerPage = 20;
		pageBean.setRowsPerPage(rowsPerPage);
		
		if (operation.equalsIgnoreCase("search") || operation.equalsIgnoreCase("select")) {
			String id = request.getParameter("id");
			String temp = "";
			//点击树形菜单，根据选中的编号查询
			if(id!=null && !id.equals(""))
			{
				String tail = id.substring(1);
				if( tail.equals("000"))// Main type
				{
					temp += " and a.PRID=?";
					request.setAttribute("RID", id);
				}
				else
				{
					temp += " and a.RID=?";
				}
				params = new String[]{id};
			}
			else
			{
				String name = mistypeManageForm.getName();
				if(name != null && !name.equals(""))
				{
					temp += " and a.RNAME like ?";
					params = new String[]{"%" + name + "%"};
				}
			}
			sql = "select a.*,b.RNAME as PNAME from SYS_JBREASON a, SYS_JBREASON b where a.PRID=b.RID " + temp + " order by RID asc";
			request.getSession().setAttribute("queryMistypeSql", sql);
			request.getSession().setAttribute("queryMistypeParams", params);
		}
		else if(operation.equalsIgnoreCase("changePage")){
			sql = (String)request.getSession().getAttribute("queryMistypeSql");
			params = (String[])request.getSession().getAttribute("queryMistypeParams");
			if (request.getParameter("pageNum") != null && request.getParameter("pageNum") != "") {
				queryPageNo = Integer.parseInt(request.getParameter("pageNum"));
			}
		}
		pageBean.setQuerySql(sql);
		pageBean.setParams(params);
		pageBean.setQueryPageNo(queryPageNo);
		DBTools db = new DBTools();
		ResultSet rs = db.queryRs(queryPageNo, pageBean, rowsPerPage);
		ArrayList result = db.queryMistypeList(rs, rowsPerPage);
		if(result.size() > 0)
		{
			mistypeManageForm.setRecordNotFind("false");
			mistypeManageForm.setRecordList(result);
			
			SystemShare.SplitPageFun(request, pageBean, 1);
		}
		else
		{
			mistypeManageForm.setRecordNotFind("true");
			
			SystemShare.SplitPageFun(request, pageBean, 0);
		}
		//添加完组织之后，会自动刷新页面；如果直接跳转到dicList页面，则左侧的组织机构树将会不显示，出现问题！设置该变量用于控制页面的跳转
		String type =(String) request.getSession().getAttribute("configMistypeFlag");
		if(type == null || type.equals(""))
		{
			//跳转到mistypeList.jsp
			return mapping.findForward("initMistype");
		}
		else if(type.equals("true"))
		{
			//跳转到mistypeManage.jsp
			request.getSession().setAttribute("configMistypeFlag", "");
			return mapping.findForward("init");
		}
		return null;
	}
	/**
	 * 删除mistype信息
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		
		String type = request.getParameter("type");
		
		String ids = request.getParameter("ids");
		DBTools dbTool = new DBTools();
		boolean result = true;
		if(ids == null || ids.equals(""))
		{
			String id = request.getParameter("id");
			result = dbTool.deleteItemReal(id, "SYS_JBREASON", "ID");
		}
		else
		{
			String[] arrID = ids.split(",");
			result = dbTool.deleteItemsReal(arrID, "SYS_JBREASON", "ID");
		}
		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result)
		{
			request.getSession().setAttribute("configMistypeFlag", "true");
			json.put("statusCode", 200);
			json.put("message", "删除成功！");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", "删除失败！");
		}
		out.write(json.toString());
		out.flush();
		out.close();
		
		return null;
	}

}