/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.expertAndDept;

import java.io.UnsupportedEncodingException;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.whu.tools.DBTools;

/** 
 * MyEclipse Struts
 * Creation date: 04-13-2015
 * 
 * XDoclet definition:
 * @struts.action path="deptFKManageAction" name="deptFKManageForm" parameter="method" scope="request" validate="true"
 */
public class DeptFKManageAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	public ActionForward eventList(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DeptFKManageForm deptFKForm = (DeptFKManageForm)form;
		String loginName = (String)request.getSession().getAttribute("LoginName");
		String sql = "select a.ID,a.REPORTID,a.ISSUBMIT,a.ADVICEID,b.TITLE,b.DEPTNAME,b.SHORTINFO,b.FKTIME,b.SURVEYCONTENT,b.FILEPATH,c.STATUS from TB_ED_ADVICE a, TB_DEPTSURVEYLETTER b, TB_REPORTINFO c where a.ADVICEID=b.DEPTADVICEID and a.LOGINNAME=? and a.REPORTID=c.REPORTID";
		DBTools db = new DBTools();
		ArrayList result = db.queryDeptDCList(sql, new String[]{loginName});
		if(result.size() > 0)
		{
			deptFKForm.setRecordNotFind("false");
			deptFKForm.setRecordList(result);
			request.setAttribute("totalRows",String.valueOf(result.size()));
		}
		else
		{
			deptFKForm.setRecordNotFind("true");
			request.setAttribute("totalRows",String.valueOf(0));
		}
		return mapping.findForward("deptDCList");
	}
	/**
	 * 跳转到在线提交调查结论页面
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws UnsupportedEncodingException
	 */
	public ActionForward onlineSubmit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws UnsupportedEncodingException {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		DeptFKManageForm deptFKForm = (DeptFKManageForm)form;
		String id = request.getParameter("id");
		String reportID = request.getParameter("reportID");
		String adviceID = request.getParameter("adviceID");
		DBTools dbTools = new DBTools();
		//String sql = "select a.*,b.TITLE from TB_ED_ADVICE a,TB_DEPTSURVEYLETTER where a.ID=" + id + " and a.ADVICEID=b.DEPTADVICEID";
		
		String title = dbTools.querySingleData("TB_DEPTSURVEYLETTER", "TITLE", "DEPTADVICEID", adviceID);
		request.setAttribute("title", title);
		
		String sql = "select a.ADVICE,a.EXPERTADVICE,a.ATTACHNAME,b.LITIGANTNAME,b.LITIGANTTIME,b.LITIGANTCONTENT from TB_DEPTADVICE a, TB_LITIGANTSTATE b where a.ID=b.DEPTADVICEID and a.ID=?";
		DeptAdviceBean dab = dbTools.queryDeptAdvice(sql, new String[]{adviceID},reportID);
		ArrayList result = new ArrayList();
		result.add(dab);
		deptFKForm.setRecordList(result);

		request.setAttribute("dcID", id);
		request.setAttribute("reportID", reportID);
		request.setAttribute("adviceID", adviceID);
		
		// if submit, cannot edit separate in deptAdviceFk.jsp
		String loginName = (String)request.getSession().getAttribute("LoginName");
		String isSubmit = dbTools.querySingleData("TB_ED_ADVICE", "ISSUBMIT", "LOGINNAME", loginName);
		request.setAttribute("isSubmit", isSubmit);
		
		return mapping.findForward("onlineSubmit");
	}
//	public ActionForward onlineSubmit(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) throws UnsupportedEncodingException {
//		response.setContentType("text/html;charset=utf-8");
//		request.setCharacterEncoding("utf-8");
//		DeptFKManageForm deptFKForm = (DeptFKManageForm)form;
//		String id = request.getParameter("id");
//		String reportID = request.getParameter("reportID");
//		String adviceID = request.getParameter("adviceID");
//		DBTools dbTools = new DBTools();
//		//String sql = "select a.*,b.TITLE from TB_ED_ADVICE a,TB_DEPTSURVEYLETTER where a.ID=" + id + " and a.ADVICEID=b.DEPTADVICEID";
//		
//		String title = dbTools.querySingleData("TB_DEPTSURVEYLETTER", "TITLE", "DEPTADVICEID", adviceID);
//		request.setAttribute("title", title);
//		
//		String sql = "select a.ADVICE,a.EXPERTADVICE,a.ATTACHNAME,b.LITIGANTNAME,b.LITIGANTTIME,b.LITIGANTCONTENT from TB_DEPTADVICE a, TB_LITIGANTSTATE b where a.ID=b.DEPTADVICEID and a.ID=?";
//		DeptAdviceBean dab = dbTools.queryDeptAdvice(sql, new String[]{adviceID},reportID);
//		ArrayList result = new ArrayList();
//		if(dab==null)
//		{
//			dab = new DeptAdviceBean();
//			dab.setDeptAdvice("");
//			dab.setLitigantName("");
//			dab.setAttitude("");
//			dab.setLitigantTime("");
//			dab.setExpertAdvice("");
//		}
//		result.add(dab);System.out.println(dab.toString());
//		deptFKForm.setRecordList(result);
//
//		request.setAttribute("dcID", id);
//		request.setAttribute("reportID", reportID);
//		request.setAttribute("adviceID", adviceID);
//		
//		// if submit, cannot edit separate in deptAdviceFk.jsp
//		String loginName = (String)request.getSession().getAttribute("LoginName");
//		String isSubmit = dbTools.querySingleData("TB_ED_ADVICE", "ISSUBMIT", "LOGINNAME", loginName);
//		request.setAttribute("isSubmit", isSubmit);
//		
//		return mapping.findForward("onlineSubmit");
//	}
}