/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.eventmanage;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-03-2013
 * 
 * XDoclet definition:
 * @struts.form name="approveEventForm"
 */
public class ApproveEventForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	//事件编号
	private String reportID;
	//是否立案
	private String isLA;
	//是否需要“依托单位鉴定”、“专家鉴定”和“当事人陈述”
	private String isXY;
	//立案意见
	private String laAdvice;
	//审核人
	private String approveName;
	private String recordNotFind="false";
	private List recordList=null;
	private String operation = null;
	private String officer;
	
	public String getOfficer() {
		return officer;
	}

	public void setOfficer(String officer) {
		this.officer = officer;
	}


	public String getOperation() {
		return operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}
	
	public String getRecordNotFind() {
		return recordNotFind;
	}

	public  void setRecordNotFind(String recordNotFind) {
		this.recordNotFind = recordNotFind;
	}
	
	public List getRecordList() {
		return recordList;
	}

	public void setRecordList(List recordList) {
		this.recordList = recordList;
	}
	
	public String getReportID() {
		return reportID;
	}

	public void setReportID(String reportID) {
		this.reportID = reportID;
	}

	public String getIsLA() {
		return isLA;
	}

	public void setIsLA(String isLA) {
		this.isLA = isLA;
	}
	
	public String getIsXY() {
		return isXY;
	}

	public void setIsXY(String isXY) {
		this.isXY = isXY;
	}

	public String getLaAdvice() {
		return laAdvice;
	}

	public void setLaAdvice(String laAdvice) {
		this.laAdvice = laAdvice;
	}

	public String getApproveName() {
		return approveName;
	}

	public void setApproveName(String approveName) {
		this.approveName = approveName;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}