/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.eventmanage;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 01-20-2013
 * 
 * XDoclet definition:
 * @struts.form name="deptAdviceForm"
 */
public class DeptAdviceForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String id;
	private String reportID;
	private String dept;
	private String time;
	private String advice;
	private String deptAdvice;
	private String attitude;
	private String talkRecorder;
	private String expertAdvice;
	private String fileName;
	private FormFile file;
	private String serialNum;
	private String litigantName;
	private String litigantTime;
	private String fileExtFlag;
	
	//调查函标示
	private String letterFlag;
	private String title;
	private String deptName;
	private String shortInfo;
	private String fkTime;
	private String surveyContent;
	
	private String loginName;
	private String password;
	private String dchID;
	private String adviceID;
	
	private String recordNotFind = "false";
	private List recordList = null;

	public String getDchID() {
		return dchID;
	}

	public void setDchID(String dchID) {
		this.dchID = dchID;
	}

	public String getAdviceID() {
		return adviceID;
	}

	public void setAdviceID(String adviceID) {
		this.adviceID = adviceID;
	}

	public String getRecordNotFind() {
		return recordNotFind;
	}

	public void setRecordNotFind(String recordNotFind) {
		this.recordNotFind = recordNotFind;
	}

	public List getRecordList() {
		return recordList;
	}

	public void setRecordList(List recordList) {
		this.recordList = recordList;
	}

	public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFileExtFlag() {
		return fileExtFlag;
	}

	public void setFileExtFlag(String fileExtFlag) {
		this.fileExtFlag = fileExtFlag;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getFkTime() {
		return fkTime;
	}

	public void setFkTime(String fkTime) {
		this.fkTime = fkTime;
	}

	public String getLetterFlag() {
		return letterFlag;
	}

	public void setLetterFlag(String letterFlag) {
		this.letterFlag = letterFlag;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getShortInfo() {
		return shortInfo;
	}

	public void setShortInfo(String shortInfo) {
		this.shortInfo = shortInfo;
	}

	public String getSurveyContent() {
		return surveyContent;
	}

	public void setSurveyContent(String surveyContent) {
		this.surveyContent = surveyContent;
	}

	public String getLitigantTime() {
		return litigantTime;
	}

	public void setLitigantTime(String litigantTime) {
		this.litigantTime = litigantTime;
	}

	public String getLitigantName() {
		return litigantName;
	}

	public void setLitigantName(String litigantName) {
		this.litigantName = litigantName;
	}

	public String getSerialNum() {
		return serialNum;
	}

	public void setSerialNum(String serialNum) {
		this.serialNum = serialNum;
	}

	public String getDeptAdvice() {
		return deptAdvice;
	}

	public void setDeptAdvice(String deptAdvice) {
		this.deptAdvice = deptAdvice;
	}

	public String getAttitude() {
		return attitude;
	}

	public void setAttitude(String attitude) {
		this.attitude = attitude;
	}

	public String getTalkRecorder() {
		return talkRecorder;
	}

	public void setTalkRecorder(String talkRecorder) {
		this.talkRecorder = talkRecorder;
	}

	public String getExpertAdvice() {
		return expertAdvice;
	}

	public void setExpertAdvice(String expertAdvice) {
		this.expertAdvice = expertAdvice;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public FormFile getFile() {
		return file;
	}

	public void setFile(FormFile file) {
		this.file = file;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getReportID() {
		return reportID;
	}

	public void setReportID(String reportID) {
		this.reportID = reportID;
	}

	public String getDept() {
		return dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getAdvice() {
		return advice;
	}

	public void setAdvice(String advice) {
		this.advice = advice;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}