/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.eventmanage;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import java.util.ArrayList;
import java.util.List;
import java.io.PrintWriter;

import net.sf.json.JSONObject;

import java.sql.ResultSet;

import com.whu.tools.DBTools;
import com.whu.tools.CheckPage;
import com.whu.web.user.UserBean;
import com.whu.web.common.SystemShare;
import com.whu.tools.SystemConstant;

/** 
 * MyEclipse Struts
 * Creation date: 01-14-2015
 * 
 * XDoclet definition:
 * @struts.action path="/dispatchEventAction" name="dispatchManageForm" input="/web/eventManage/dispatchEvent.jsp" parameter="method" scope="request" validate="true"
 * @struts.action-forward name="init" path="/web/eventManage/dispatchEvent.jsp"
 */
public class DispatchEventAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	
	public ActionForward init( ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {		
		DispatchEventForm dispatchEventForm = (DispatchEventForm)form;
	
		CheckPage pageBean = new CheckPage();
		int queryPageNo = 1;
		int rowsPerPage = 20;
		pageBean.setRowsPerPage(rowsPerPage);
	
		
		pageBean.setQueryPageNo(queryPageNo);
		String sql = "select ID,LOGINNAME,USERNAME,DISPATCHCHECKED from SYS_USER where POSIDS='9'";
		String[] params = new String[0];
		request.getSession().setAttribute("queryOfficerSql", sql);
		request.getSession().setAttribute("queryOfficerParams", params);
		pageBean.setQuerySql(sql);
		pageBean.setParams(params);
		DBTools db = new DBTools();
		ResultSet rs = db.queryRs(queryPageNo, pageBean, rowsPerPage);
		ArrayList result = db.queryOfficerList(rs, rowsPerPage);
		if(result.size() > 0)
		{
			dispatchEventForm.setRecordNotFind("false");
			dispatchEventForm.setRecordList(result);
			SystemShare.SplitPageFun(request, pageBean, 1);
		}
		else
		{
			dispatchEventForm.setRecordNotFind("true");
			SystemShare.SplitPageFun(request, pageBean, 0);
		}
		return mapping.findForward("init");
	}
	
	
	public ActionForward queryMsg(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");	
		
		DispatchEventForm dispatchEventForm = (DispatchEventForm)form;
		String operation = request.getParameter("operation");
		CheckPage pageBean = new CheckPage();
		String sql = "";
		String[] params = new String[0];
		int queryPageNo = 1;
		int rowsPerPage = 20;
		pageBean.setRowsPerPage(rowsPerPage);
		if (operation.equalsIgnoreCase("search")) {
			String officer = dispatchEventForm.getOfficer();
			String temp = "";
			if(officer != null && !officer.equals(""))
			{
				temp += " and USERNAME like ?";
				params = new String[]{"%" + officer + "%"};
			}
			sql = "select ID,USERNAME,LOGINNAME from SYS_USER where POSIDS=9 " + temp;
			request.getSession().setAttribute("queryOfficerSql", sql);	
			request.getSession().setAttribute("queryOfficerParams", params);
		}
		else if(operation.equalsIgnoreCase("changePage")){
			sql = (String)request.getSession().getAttribute("queryOfficerSql");
			params = (String[])request.getSession().getAttribute("queryOfficerParams");
			if (request.getParameter("pageNum") != null && request.getParameter("pageNum") != "") {
				queryPageNo = Integer.parseInt(request.getParameter("pageNum"));
			}
		}
		pageBean.setQuerySql(sql);
		pageBean.setParams(params);
		pageBean.setQueryPageNo(queryPageNo);
		DBTools db = new DBTools();
		ResultSet rs = db.queryRs(queryPageNo, pageBean, rowsPerPage);
		ArrayList result = db.queryOfficerList(rs, rowsPerPage);
		if(result.size() > 0)
		{
			dispatchEventForm.setRecordNotFind("false");
			dispatchEventForm.setRecordList(result);
			
			SystemShare.SplitPageFun(request, pageBean, 1);
		}
		else
		{
			dispatchEventForm.setRecordNotFind("true");
			
			SystemShare.SplitPageFun(request, pageBean, 0);
		}
		return mapping.findForward("init");
	}
	
	public ActionForward dispatch(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		String reportID = request.getParameter("reportID");//
		String userIds = request.getParameter("ids");//6,11
		
		String[] userId = userIds.split(",");
		String[] newOfficerUserName =new String[userId.length];
		String[] newOfficerLoginName=new String[userId.length];
		
		String userID;
		String T_R_Officer;
		DBTools dbTool = new DBTools();
		// get officer before and now associated to this serialNum;
		String Tb_ReportInfo_Officers=dbTool.querySingleData("TB_REPORTINFO", "OFFICER", "REPORTID", reportID);
		String[] Tb_ReportInfo_Officer =new String[0];
		if(Tb_ReportInfo_Officers!=null)
		{
			Tb_ReportInfo_Officer = Tb_ReportInfo_Officers.split(",");
		}
		String[] oldOfficerUserName=new String[Tb_ReportInfo_Officer.length];
		if(Tb_ReportInfo_Officers!=null)
		{
			for(int j = 0; j < Tb_ReportInfo_Officer.length; j ++)
			{
				T_R_Officer=Tb_ReportInfo_Officer[j];
				oldOfficerUserName[j] = dbTool.querySingleData("SYS_USER", "USERNAME", "LOGINNAME", T_R_Officer);
			}
		}
		
		for(int i = 0; i < userId.length; i ++)
		{
			userID=userId[i];
			newOfficerUserName[i] = dbTool.querySingleData("SYS_USER", "USERNAME", "ID", userID);
			newOfficerLoginName[i] = dbTool.querySingleData("SYS_USER", "LOGINNAME", "ID", userID);
		}
		
		String newOfficerUserNames=StringUtils.join(newOfficerUserName, ",");
		String newOfficerLoginNames=StringUtils.join(newOfficerLoginName, ",");
		request.getSession().setAttribute("OFFICER",newOfficerUserNames);
		// get status, if like 4% prevent dispatch
		String status = dbTool.querySingleData("TB_REPORTINFO", "STATUS", "REPORTID", reportID);
		String serialNum = dbTool.querySingleData("TB_REPORTINFO", "SERIALNUM", "REPORTID", reportID);
				
		boolean result = true;
		if (status.charAt(0) == '4') {
			result = false;
		}
		
		if (result) {
			String sql = "update TB_REPORTINFO set OFFICER=? where REPORTID=?";
			result = dbTool.insertItem(sql, new String[]{newOfficerLoginNames, reportID});
		}
		
		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result)
		{
			String userName = (String)request.getSession().getAttribute("UserName"); // operator name
			if (oldOfficerUserName != null && !oldOfficerUserName.equals("")) {
				dbTool.insertLogInfo(userName, SystemConstant.LOG_DISPATCH, "从 " + Tb_ReportInfo_Officers + " 分派案件 " + serialNum + " 给： " + newOfficerUserName, request.getRemoteAddr());
			} else {
				dbTool.insertLogInfo(userName, SystemConstant.LOG_DISPATCH, "分派案件 " + serialNum + " 给： " + newOfficerUserNames, request.getRemoteAddr());
			}
			//插入处理过程到数据库中
			String describe = userName + "分派案件 " + serialNum + " 给： " +  newOfficerUserNames;
			result = dbTool.InsertHandleProcess(reportID, userName, SystemConstant.HP_DISPACH, SystemConstant.SS_SURVEYING, SystemConstant.LCT_DISPATCH, describe);
			
			json.put("statusCode", 200);
			json.put("message", " 指派成功！");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", " 指派失败！");
			if (status.charAt(0) == '4') {
				json.put("message", "事件已结束! 无法指派! ");
			}
		}
		json.put("callbackType", "closeCurrent");
		out.write(json.toString());
		out.flush();
		out.close();
		
		return null;

	}
	
}