/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.eventmanage;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-29-2014
 * 
 * XDoclet definition:
 * @struts.form name="eventFKForm"
 */
public class EventFKForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String recordNotFind = "false";
	private List recordList = null;
	private String fkName;
	private String fkBeginTime;
	private String fkEndTime;
	public String getFkName() {
		return fkName;
	}

	public void setFkName(String fkName) {
		this.fkName = fkName;
	}

	public String getFkBeginTime() {
		return fkBeginTime;
	}

	public void setFkBeginTime(String fkBeginTime) {
		this.fkBeginTime = fkBeginTime;
	}

	public String getFkEndTime() {
		return fkEndTime;
	}

	public void setFkEndTime(String fkEndTime) {
		this.fkEndTime = fkEndTime;
	}

	public String getRecordNotFind() {
		return recordNotFind;
	}

	public void setRecordNotFind(String recordNotFind) {
		this.recordNotFind = recordNotFind;
	}

	public List getRecordList() {
		return recordList;
	}

	public void setRecordList(List recordList) {
		this.recordList = recordList;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}