/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.eventmanage;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-31-2014
 * 
 * XDoclet definition:
 * @struts.form name="fYApplyManageForm"
 */
public class FYApplyManageForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	private String id;
	private String reportID;
	private String fyApplyName;
	private String fyTime;
	private String shortInfo;
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getReportID() {
		return reportID;
	}

	public void setReportID(String reportID) {
		this.reportID = reportID;
	}

	public String getFyApplyName() {
		return fyApplyName;
	}

	public void setFyApplyName(String fyApplyName) {
		this.fyApplyName = fyApplyName;
	}

	public String getFyTime() {
		return fyTime;
	}

	public void setFyTime(String fyTime) {
		this.fyTime = fyTime;
	}

	public String getShortInfo() {
		return shortInfo;
	}

	public void setShortInfo(String shortInfo) {
		this.shortInfo = shortInfo;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}