/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.eventmanage;

import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONObject;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.whu.tools.DBTools;
import com.whu.tools.SystemConstant;
import com.whu.web.common.SystemShare;
import com.whu.web.eventbean.FYApply;
import com.whu.web.eventbean.HandleDecide;

/** 
 * MyEclipse Struts
 * Creation date: 03-31-2014
 * 
 * XDoclet definition:
 * @struts.action path="/fYApplyManageAction" name="fYApplyManageForm" parameter="method" scope="request" validate="true"
 */
public class FYApplyManageAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	public ActionForward save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		FYApplyManageForm fyApplyManageForm = (FYApplyManageForm) form;
		boolean result = false;
		String loginName = (String)request.getSession().getAttribute("LoginName");
		DBTools dbTools = new DBTools();
		String reportID = fyApplyManageForm.getReportID();
		String fyApplyName = fyApplyManageForm.getFyApplyName();
		String fyTime = fyApplyManageForm.getFyTime();
		String shortInfo = fyApplyManageForm.getShortInfo();
		String id = fyApplyManageForm.getId();
		String sql = "";
		String[] params = new String[0];
		boolean editFlag = false;
		//如果不为空，则说明是编辑
		if(id != null && !id.equals(""))
		{
			editFlag = true;
		}
		String filePath = request.getSession().getServletContext().getRealPath("/")+"/attachment/";
		//String path1 = filePath + "temp";
		String path1 = request.getSession().getServletContext().getRealPath("/") + "/temp/" + loginName + "/";
		String path2 = filePath + reportID;
		//将临时文件夹中的附件转存到以警情编号为目录的文件夹下
		//获得服务器的IP地址路径，存放在数据库中，便于下载
		String relDirectory = "attachment" + "/" + reportID;
		String createName = (String)request.getSession().getAttribute("UserName");
		result = SystemShare.IOCopy(path1, path2, relDirectory, createName);
		
		String fyAttachName = (String)request.getSession().getAttribute("FYApplyAttach");
		if(fyAttachName != null && !fyAttachName.equals(""))
		{
			fyAttachName = "attachment/" + reportID + "/" + fyAttachName;
			request.getSession().setAttribute("FYApplyAttach", "");
		}
		else
		{
			fyAttachName = "";
		}
		
		if(!editFlag)//新增异议申请
		{
			sql = "insert into TB_FYAPPLY(REPORTID,FYAPPLYNAME,FYTIME,SHORTINFO,ATTACHPATH) values(?, ?, ?, ?, ?)";
			params = new String[]{reportID, fyApplyName, fyTime, shortInfo, fyAttachName};
			result = dbTools.insertItem(sql, params);
			
			if(result)
			{
				
	    		String time = SystemShare.GetNowTime("yyyy-MM-dd");
	    		
				sql = "update TB_REPORTINFO set STATUS=?,LASTTIME=? where REPORTID=?";
				params = new String[]{SystemConstant.SS_FYAPPLY, time, reportID};
				result = dbTools.insertItem(sql, params);
				
				String describe = time + "," + createName + "编辑" + fyApplyName + "的复议申请";
				//插入处理过程到数据库中
				result = dbTools.InsertHandleProcess(reportID, createName, SystemConstant.HP_FYAPPLY, SystemConstant.SS_FYAPPLY, SystemConstant.LCT_FYSQ, describe);
			}
		}
		else// 编辑复议申请
		{
			if(fyAttachName.equals(""))//如果没有上传附件，则不更新附件路径
			{
				sql = "update TB_FYAPPLY set FYAPPLYNAME=?, FYTIME=?, SHORTINFO=? where ID=?";
				params = new String[]{fyApplyName, fyTime, shortInfo, id};
			}
			else//如果重新上传了附件，则更新路径信息
			{
				sql = "update TB_FYAPPLY set FYAPPLYNAME=?, FYTIME=?, SHORTINFO=?, ATTACHPATH=? where ID=?";
				params = new String[]{fyApplyName, fyTime, shortInfo, fyAttachName, id};
			}
			result = dbTools.insertItem(sql, params);
		}

		//写入日志文件
		dbTools.insertLogInfo(createName, SystemConstant.LOG_FYAPPLY, "编辑复议申请信息，事件编号为：" + reportID, request.getRemoteAddr());
		
		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result)
		{
			//防止高级检索功能模块执行
			request.getSession().setAttribute("GjSearch", "false");
			json.put("statusCode", 200);
			json.put("message", "保存成功！");
			//json.put("callbackType", "closeCurrent");
			json.put("navTabId", "addFYApply");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", "保存失败！");
		}
		out.write(json.toString());
		out.flush();
		out.close();
		return null;
	}
	/**
	 * 删除复议申请，连同附件一起删除
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws Exception
	 */
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		
		String ids = request.getParameter("ids");
		DBTools dbTool = new DBTools();
		
		boolean result = true;
		if(ids == null || ids.equals(""))
		{
			String id = request.getParameter("id");
			String dirPath = request.getSession().getServletContext().getRealPath("/");
			String sql = "select * from TB_FYAPPLY where ID=?";
			FYApply fyApply = dbTool.queryFYApplyInfo(sql, new String[]{id});
			if(fyApply != null)
			{
				String filePath = fyApply.getAttachPath();
				if(filePath != null && !filePath.equals(""))
				{
					//删除处理决定文档
					filePath = dirPath + "/" + filePath;
					result = SystemShare.deleteFileFromDisk(filePath);
					//如果存在swf文件，则也一起删除
					filePath = filePath.substring(0, filePath.lastIndexOf("."));
					filePath = filePath + ".swf";
					result = SystemShare.deleteFileFromDisk(filePath);
				}
			}
			result = dbTool.deleteItemReal(id, "TB_FYAPPLY", "ID");
		}
		else
		{
			String[] arrID = ids.split(",");
			result = dbTool.deleteItemsReal(arrID, "TB_FYAPPLY", "ID");
		}
		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result)
		{
			json.put("statusCode", 200);
			json.put("message", "删除成功！");
			json.put("navTabId", "addFYApply");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", "删除失败！");
		}
		out.write(json.toString());
		out.flush();
		out.close();
		
		return null;
	}
}