/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.eventmanage;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONObject;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.whu.tools.DBTools;
import com.whu.tools.SystemConstant;
import com.whu.web.common.SystemShare;

/** 
 * MyEclipse Struts
 * Creation date: 01-20-2013
 * 
 * XDoclet definition:
 * @struts.action path="/litigantStateAction" name="litigantStateForm" parameter="method" scope="request" validate="true"
 */
public class LitigantStateAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	public ActionForward save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		LitigantStateForm litigantStateForm = (LitigantStateForm)form;
		String name = litigantStateForm.getLitigantName();
		String time = litigantStateForm.getLitigantTime();
		if(time == null || time.equals(""))
			time = SystemShare.GetNowTime("yyyy-MM-dd");
		String content = litigantStateForm.getLitigantContent();
		String reportID = litigantStateForm.getReportID();
		String id = litigantStateForm.getId();
		String talkRecorder = litigantStateForm.getTalkRecorder();
		
		String attachName = (String)request.getSession().getAttribute("EventAttachName");
		if(attachName != null && !attachName.equals(""))
		{
			attachName = reportID + "/" + attachName;
			request.getSession().setAttribute("EventAttachName", "");
		}
		else
		{
			attachName = "";
		}
		
		String sql = "";
		String[] params = new String[0];
		//如果不为空，则说明是编辑
		if(id != null && !id.equals(""))
		{
			if(attachName.equals(""))
			{
				sql = "update TB_LITIGANTSTATE set LITIGANTNAME=?, LITIGANTTIME=?,LITIGANTCONTENT=?,TALKRECORDER=? where ID=?";
				params = new String[]{name, time, content, talkRecorder, id};
			}
			else
			{
				sql = "update TB_LITIGANTSTATE set LITIGANTNAME=?, LITIGANTTIME=?,LITIGANTCONTENT=?,TALKRECORDER=?,ATTACHNAME=? where ID=?";
				params = new String[]{name, time, content, talkRecorder, attachName, id};
			}
			
		}
		else//如果为空，则说明是新增
		{
			sql = "insert into TB_LITIGANTSTATE(REPORTID,LITIGANTNAME,LITIGANTTIME,LITIGANTCONTENT,TALKRECORDER,ATTACHNAME) values(?, ?, ?, ?, ?, ?)";
			params = new String[]{reportID, name, time, content, talkRecorder, attachName};
		}
		
		String filePath = request.getSession().getServletContext().getRealPath("/")+"/attachment/";
		//String path1 = filePath + "temp";
		String loginName = (String)request.getSession().getAttribute("LoginName");
		String path1 = request.getSession().getServletContext().getRealPath("/") + "/temp/" + loginName + "/";
		String path2 = filePath + reportID;
		//获得服务器的IP地址路径，存放在数据库中，便于下载
		String relDirectory = "attachment" + "/" + reportID;
		//将临时文件夹中的附件转存到以警情编号为目录的文件夹下
		String createName = (String)request.getSession().getAttribute("UserName");
		boolean result = SystemShare.IOCopy(path1, path2, relDirectory, createName);
		
		DBTools dbTools = new DBTools();
		result = dbTools.insertItem(sql, params);
		
		if(result)
		{
			String describe = time + "," + createName + "编辑当事人陈述信息";
			//插入处理过程到数据库中
			result = dbTools.InsertHandleProcess(reportID, createName, SystemConstant.HP_LIGITANTSTATE, SystemConstant.SS_SURVEYING, SystemConstant.LCT_CS, describe);
			//写入日志文件
			dbTools.insertLogInfo(createName, SystemConstant.LOG_LITIGANTSTATE, "编辑当事人陈述信息，事件编号为：" + reportID, request.getRemoteAddr());
			//更新事件的最近一次操作时间
			result = dbTools.UpdateLastTime(reportID);
		}
		
		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result)
		{
			//防止高级检索功能模块执行
			request.getSession().setAttribute("GjSearch", "false");
			json.put("statusCode", 200);
			json.put("message", "保存成功！");
			//json.put("callbackType", "closeCurrent");
			json.put("navTabId", "addLitigantState");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", "保存失败！");
		}
		out.write(json.toString());
		out.flush();
		out.close();
		return null;
	}
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		String ids = request.getParameter("ids");
		DBTools dbTool = new DBTools();
		boolean result = true;
		if(ids == null || ids.equals(""))
		{
			String id = request.getParameter("id");
			result = dbTool.deleteItemReal(id, "TB_LITIGANTSTATE", "ID");
		}
		else
		{
			String[] arrID = ids.split(",");
			result = dbTool.deleteItemsReal(arrID, "TB_LITIGANTSTATE", "ID");
		}
		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result)
		{
			//防止高级检索功能模块执行
			request.getSession().setAttribute("GjSearch", "false");
			json.put("statusCode", 200);
			json.put("message", "删除当事人陈述成功");
			json.put("navTabId", "addLitigantState");
			//json.put("rel", "addDeptAdvice");
			//json.put("callbackType", "closeCurrent");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", "删除当事人陈述失败！");
		}
		out.write(json.toString());
		out.flush();
		out.close();
		
		return null;
	}
}