/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.eventmanage;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-06-2014
 * 
 * XDoclet definition:
 * @struts.form name="lookUpGroupForm"
 */
public class LookUpGroupForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String recordNotFind = "false";
	private List recordList = null;
	//会议名称
	private String meetName;
	//用户姓名
	private String userName;
	//举报对象
	private String jbObject;
	//组织名称
	private String zzName;
	//角色名称
	private String roleName;
	//职务名称
	private String posName;
	//邮箱联系人姓名
	private String contactName;
	//专家姓名
	private String expertName;
	//专家所属学部
	private String expertFaculty;
	//处理决定
	private String cljd;
	//委员姓名
	private String wyName;
	public String getWyName() {
		return wyName;
	}

	public void setWyName(String wyName) {
		this.wyName = wyName;
	}

	public String getCljd() {
		return cljd;
	}

	public void setCljd(String cljd) {
		this.cljd = cljd;
	}

	public String getExpertName() {
		return expertName;
	}

	public void setExpertName(String expertName) {
		this.expertName = expertName;
	}

	public String getExpertFaculty() {
		return expertFaculty;
	}

	public void setExpertFaculty(String expertFaculty) {
		this.expertFaculty = expertFaculty;
	}

	public String getContactName() {
		return contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getPosName() {
		return posName;
	}

	public void setPosName(String posName) {
		this.posName = posName;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getZzName() {
		return zzName;
	}

	public void setZzName(String zzName) {
		this.zzName = zzName;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getJbObject() {
		return jbObject;
	}

	public void setJbObject(String jbObject) {
		this.jbObject = jbObject;
	}

	public String getMeetName() {
		return meetName;
	}

	public void setMeetName(String meetName) {
		this.meetName = meetName;
	}

	public String getRecordNotFind() {
		return recordNotFind;
	}

	public void setRecordNotFind(String recordNotFind) {
		this.recordNotFind = recordNotFind;
	}

	public List getRecordList() {
		return recordList;
	}

	public void setRecordList(List recordList) {
		this.recordList = recordList;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}