/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.eventmanage;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-18-2014
 * 
 * XDoclet definition:
 * @struts.form name="tjManageForm"
 */
public class TjManageForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String tjBeginTime;
	private String tjEndTime;
	//状态统计
	private String statusTj = "true";
	//受理数与立案数比较
	private String numCompare = "false";
	//统计方式，1为状态统计，2为受理与立案统计
	private String type;
	//受理数与立案数统计时的年份输入
	private String tjYear;
	private String recordNotFind = "false";
	private List recordList = null;
	private String reportName;
	private String serialNum;
	private String jbBeginTime;
	private String jbEndTime;
	private String beReportName;
	public String getReportName() {
		return reportName;
	}

	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	public String getSerialNum() {
		return serialNum;
	}

	public void setSerialNum(String serialNum) {
		this.serialNum = serialNum;
	}

	public String getJbBeginTime() {
		return jbBeginTime;
	}

	public void setJbBeginTime(String jbBeginTime) {
		this.jbBeginTime = jbBeginTime;
	}

	public String getJbEndTime() {
		return jbEndTime;
	}

	public void setJbEndTime(String jbEndTime) {
		this.jbEndTime = jbEndTime;
	}

	public String getBeReportName() {
		return beReportName;
	}

	public void setBeReportName(String beReportName) {
		this.beReportName = beReportName;
	}

	public String getRecordNotFind() {
		return recordNotFind;
	}

	public void setRecordNotFind(String recordNotFind) {
		this.recordNotFind = recordNotFind;
	}

	public List getRecordList() {
		return recordList;
	}

	public void setRecordList(List recordList) {
		this.recordList = recordList;
	}

	public String getTjYear() {
		return tjYear;
	}

	public void setTjYear(String tjYear) {
		this.tjYear = tjYear;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getStatusTj() {
		return statusTj;
	}

	public void setStatusTj(String statusTj) {
		this.statusTj = statusTj;
	}

	public String getNumCompare() {
		return numCompare;
	}

	public void setNumCompare(String numCompare) {
		this.numCompare = numCompare;
	}

	public String getTjBeginTime() {
		return tjBeginTime;
	}

	public void setTjBeginTime(String tjBeginTime) {
		this.tjBeginTime = tjBeginTime;
	}

	public String getTjEndTime() {
		return tjEndTime;
	}

	public void setTjEndTime(String tjEndTime) {
		this.tjEndTime = tjEndTime;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}